
export const deliveredActionTypes = {
    //DELIVEREDs
    DELIVERED_RESPONSES: "DELIVERED_RESPONSES",
    DELIVERED_RESPONSES_SUCCESS:"DELIVERED_RESPONSES_SUCCESS",
    DELIVERED_RESPONSES_ERROR: "DELIVERED_RESPONSES_ERROR",
    DELIVERED_RESPONSES_RESET:"DELIVERED_RESPONSES_RESET", 
    
    //DELIVERED_TYPE
    DELIVERED_TYPE_RESPONSES: "DELIVERED_TYPE_RESPONSES",
    DELIVERED_TYPE_RESPONSES_SUCCESS:"DELIVERED_TYPE_RESPONSES_SUCCESS",
    DELIVERED_TYPE_RESPONSES_ERROR: "DELIVERED_TYPE_RESPONSES_ERROR",
    DELIVERED_TYPE_RESPONSES_RESET:"DELIVERED_TYPE_RESPONSES_RESET", 
}
// export const SET_FIRST_EMAIL_ID = "SET_FIRST_EMAIL_ID"
// export const SET_LOGIN_MAIL = "SET_LOGIN_MAIL"

