
export const expensesActionTypes = {
    //EXPENSESs
    EXPENSES_RESPONSES: "EXPENSES_RESPONSES",
    EXPENSES_RESPONSES_SUCCESS:"EXPENSES_RESPONSES_SUCCESS",
    EXPENSES_RESPONSES_ERROR: "EXPENSES_RESPONSES_ERROR",
    EXPENSES_RESPONSES_RESET:"EXPENSES_RESPONSES_RESET", 
    
    //EXPENSES_TYPE
    EXPENSES_TYPE_RESPONSES: "EXPENSES_TYPE_RESPONSES",
    EXPENSES_TYPE_RESPONSES_SUCCESS:"EXPENSES_TYPE_RESPONSES_SUCCESS",
    EXPENSES_TYPE_RESPONSES_ERROR: "EXPENSES_TYPE_RESPONSES_ERROR",
    EXPENSES_TYPE_RESPONSES_RESET:"EXPENSES_TYPE_RESPONSES_RESET", 
}
// export const SET_FIRST_EMAIL_ID = "SET_FIRST_EMAIL_ID"
// export const SET_LOGIN_MAIL = "SET_LOGIN_MAIL"

