
export const driverActionTypes = {
    //DRIVERs
    DRIVER_RESPONSES: "DRIVER_RESPONSES",
    DRIVER_RESPONSES_SUCCESS:"DRIVER_RESPONSES_SUCCESS",
    DRIVER_RESPONSES_ERROR: "DRIVER_RESPONSES_ERROR",
    DRIVER_RESPONSES_RESET:"DRIVER_RESPONSES_RESET", 
    
    //DRIVER_TYPE
    DRIVER_TYPE_RESPONSES: "DRIVER_TYPE_RESPONSES",
    DRIVER_TYPE_RESPONSES_SUCCESS:"DRIVER_TYPE_RESPONSES_SUCCESS",
    DRIVER_TYPE_RESPONSES_ERROR: "DRIVER_TYPE_RESPONSES_ERROR",
    DRIVER_TYPE_RESPONSES_RESET:"DRIVER_TYPE_RESPONSES_RESET", 
}
// export const SET_FIRST_EMAIL_ID = "SET_FIRST_EMAIL_ID"
// export const SET_LOGIN_MAIL = "SET_LOGIN_MAIL"

