
export const DashBoardActionTypes = {
    //DASHBOARDs
    DASHBOARD_RESPONSES: "DASHBOARD_RESPONSES",
    DASHBOARD_RESPONSES_SUCCESS:"DASHBOARD_RESPONSES_SUCCESS",
    DASHBOARD_RESPONSES_ERROR: "DASHBOARD_RESPONSES_ERROR",
    DASHBOARD_RESPONSES_RESET:"DASHBOARD_RESPONSES_RESET", 
    
    //DASHBOARD_TYPE
    // DASHBOARD_TYPE_RESPONSES: "DASHBOARD_TYPE_RESPONSES",
    // DASHBOARD_TYPE_RESPONSES_SUCCESS:"DASHBOARD_TYPE_RESPONSES_SUCCESS",
    // DASHBOARD_TYPE_RESPONSES_ERROR: "DASHBOARD_TYPE_RESPONSES_ERROR",
    // DASHBOARD_TYPE_RESPONSES_RESET:"DASHBOARD_TYPE_RESPONSES_RESET", 
}
// export const SET_FIRST_EMAIL_ID = "SET_FIRST_EMAIL_ID"
// export const SET_LOGIN_MAIL = "SET_LOGIN_MAIL"

