
export const notificationActionTypes = {
    //NOTIFICATION
    NOTIFICATION_RESPONSES: "NOTIFICATION_RESPONSES",
    NOTIFICATION_RESPONSES_SUCCESS:"NOTIFICATION_RESPONSES_SUCCESS",
    NOTIFICATION_RESPONSES_ERROR: "NOTIFICATION_RESPONSES_ERROR",
    NOTIFICATION_RESPONSES_RESET:"NOTIFICATION_RESPONSES_RESET",
}
// export const SET_FIRST_EMAIL_ID = "SET_FIRST_EMAIL_ID"
// export const SET_LOGIN_MAIL = "SET_LOGIN_MAIL"

